spring:
  liquibase:
    enabled: false
  datasource:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
      username: ${POSTGRES_USER:user}
      password: ${POSTGRES_PASSWORD:password}
      driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

jwt:
  access-token-key: '{"kty":"oct","k":"UvEe/l6EH1H9M6tXhaMMayjqRg832dtLSqGQtv3xgJmnncM2J7GXayM0fJ/Po3lP"}'
  refresh-token-key: '{"kty":"oct","k":"z28JjqMOTZY85hHJ0C7Z06tbgtYeUNkc"}'