# noinspection ComposeUnknownKeys
include:
  - environment-compose.yml

services:
  app:
    build:
      context: ../
      dockerfile: docker/.Dockerfile
    container_name: app
    networks:
      - backend
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:8080'
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy